[firebase_credentials]
type = "service_account"
project_id = "capstone-1e309"
private_key_id = "a97729985ded20ec47800be6908a3929acec5202"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkqVWTKOKxwLK7\nQNCL9cQYPyXoOLWbh0TSKoFCYLpvhz7dUr/p4oYtDRMYOBih3rRtkG5/P9nRH8qk\nUHL3hG01qTSG3w/Z0e9oCUR65bUAOcTE/NAlfF+OIgU5apQ13pyG3bahtVeDvrDm\n3wB0zwLrHumuea2u2aCEcTWLfq9SbpKgLdFX1s6Aj+fBbl5wYR8nVvDXXDdJy7XE\nm/VIxD/BFYjQFCaqA2M6SKQV7kYRH3/82ddMbeg/NBK2lIv8dl5km502rlRSY6Z5\nN01jTBO6SMOzyCavQisN9xRZOE9ovszGSU+UwKO60Wsv0xxx5ITAwHWtvBaE/Hkm\nJzHkTzX/AgMBAAECggEACQYMngFuFu6n/NIK+7iOtAN16Nl+vlS15UyWA9S4Mtd3\nDvrzcHZNAxgF1VxxoSFKwvxYydlubuLuoH2WJ1FXCMtKiR+dR0MVex6S5adD+Yyw\n51ixcXR06h2cKq7YC3G1I0DwOsFs19fx6t0KsdwMXWU2yix546yies+XbxsUsZAu\nMRMFtiMnPrqAUoUgeYFV40jz9npN14ZUhSbU4gVUa4+Z3Wnws6WlD3JSD+ANlWxK\n3CtlqKvMDE2vhADenbYROmpe6+uFbARoUfIe7ffx+0CkMSZN2itUD1mmvxJIbtRD\nqhzH6RM7gIR90rKZnZhC3v/jNjHpNLstRjsbZFmroQKBgQDNwB+kOeS+RL9X0IuI\nZl9nd+brItAN3pWX/N+veSye4QLKsftwdrtyMryCDOw0CtI5Mivo6eY27RtSNjba\nbBwt/I2n56329E+We6PxAismzbQroHXBpdnSwRemIKkbHKFWuo07jiXX6Dfolpn6\ngqii43pM09ji5TWZlgeWyuQJnwKBgQDM4EEDg5mB02iP3kAIx9ZaA/x/EDq86HkC\nRIVHNhzRdcIqo7Ai92rRaRoMtWy+M6T3NgIEegUOuaYlxqfZ8Bpl+WLdFqi86jCx\nV4jSBQtnFTyRY94saDtjDP3J5/C21msxF3/qsapCIO+ppWrc/lF7fRBmW//T0IEy\ngM6Naqw3oQKBgQDHMszvmMVnmPOPt25//m07pZBB8pBv/SHj5oVCRBT5NWwYhjyj\nY7CTHZ/4YT6GHDvv+C0e8OVcJC8hZy+wRJ77vtn+x4Vb5KjxTn8opSrWBK381vtr\nIoFDVILq6hAPGabyaua11Ce7Yy5N1xD4wms2WPpdS3VeJv+/1MtAKOqijQKBgDZX\nWQc8la/oyjg2xBdQIhvYKNXvERVgOBCQ6iT8RmKMcIbsyeBMbenDjeRHDuPYQO5N\nRfW4A7VnKpmkeosE84uOvVlVFEafe3Defezu55pc+Ka7rYdr0iywmnQ+cAufDemE\niSpQG4/Uupztwk2Bq00s2/e6eT3OdSZXIfJClBFhAoGAKO3esk2KszHU7v0x9SrJ\nRbfhw6AujByOpyI609bAKTOySESqPitpJjiDTIh0tF/jKt/9PPnlbt/OjyAQq8hw\nZ/TuH5rrj7Qjoml+ZN11UJqrI510mVCdLNtPhPRpedHG1D06sGqEb0TEeaXNZXIS\nO4KWYJl6vidRfYIOvp8bs98=\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@capstone-1e309.iam.gserviceaccount.com"
client_id = "111012203141788991000"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40capstone-1e309.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[firebase_config]
apiKey = "AIzaSyCGvRGT3PvVSuXf5u9mpEcFW8yfSRT6LDQ"
authDomain = "capstone-1e309.firebaseapp.com"
projectId = "capstone-1e309"
storageBucket = "capstone-1e309.appspot.com"
databaseURL = "https://capstone-1e309.firebaseio.com"
messagingSenderId = "797647440295"
appId = "1:797647440295:web:3604ee79032556023e4e82"

[encryption]
aes_encryption_key = "EZ1N-GZUS5qLBTnD0oEPnroQN0aaccmbR6Oa3I-xbgY="
